language: python
cache:
  pip: true
  directories:
  - node_modules
matrix:
  include:
   - env: TOXENV=py27
     python: 2.7
   - env: TOXENV=py36
     python: 3.6
install:
- nvm install
- npm install
- make init
- pip install coveralls
script:
- make test-ci
- npx commitlint-travis
- npm run release -- --dry-run
after_success:
- coveralls
branches:
  except:
  - gh-pages
notifications:
  email: false
